name: Generate Metadata
on:
  push:
    branches:
      - main  # Replace with your branch name
  pull_request:
    branches:
      - main  # Replace with your branch name

jobs:
  generate-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install python-frontmatter

      - name: Generate Metadata
        run: python generate_metadata.py  # Replace with the script name or command to generate metadata
        
#       - uses: stefanzweifel/git-auto-commit-action@v4
#         with:
#           file_pattern: '*.md'
#           disable_globbing: true
