name: Generate Metadata
on:
  push:
    branches:
      - main  # Replace with your branch name
  pull_request:
    branches:
      - main  # Replace with your branch name

jobs:
  generate-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install frontmatter

      - name: Generate Metadata
        run: python generate_metadata.py  # Replace with the script name or command to generate metadata
        
      - name: Commit and push changes
        run: |
          git config --local user.name "anonymousKo"
          git config --local user.email "kore3019@gmail.com"
          git add content/posts
          git commit -m "Add metadata"
          git push
